
import { TrainingModule, Badge, ModuleStatus } from './types';

export const COACH_KITA_AVATAR = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80";
export const SUPER_ADMIN_PHONE_NUMBER = "+2250001020304";

export const TRAINING_CATALOG: TrainingModule[] = [
  {
    id: "mod_accueil_tel",
    topic: "Accueil",
    title: "L'art de l'accueil téléphonique d'élite",
    description: "Le premier contact est le moment où vous gagnez ou perdez un client. Apprenez le protocole des salons de prestige.",
    mini_course: "Votre téléphone n'est pas un outil, c'est votre première caisse enregistreuse.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. La signature vocale</h2><p>Un expert ne répond jamais par un simple « Allô ». La formule qui rassure est : <strong>« Salon [Nom], [Votre Prénom] à votre écoute, bonjour »</strong>.</p></section>`,
    coach_tip: "Souriez en parlant, votre client l'entendra à travers le téléphone.",
    strategic_mantra: "Un appel raté est un client qui part chez le voisin.",
    quiz_questions: [{ question: "Quelle est la phrase d'accueil idéale ?", options: ["Allô ?", "Salon [Nom], [Prénom] à votre écoute, bonjour", "Oui c'est pour quoi ?"], correctAnswer: 1, explanation: "Cette formule établit immédiatement votre autorité professionnelle." }],
    exercises: ["Pratiquer la signature vocale sur les 10 prochains appels."],
    tips: ["Restez calme et notez le nom du client."]
  },
  {
    id: "mod_diagnostic",
    topic: "Technique",
    title: "Le diagnostic : devenir un expert conseil",
    description: "Arrêtez de simplement couper. Apprenez à analyser pour conseiller et vendre des services de haute valeur.",
    mini_course: "Le diagnostic transforme une simple coupe en une ordonnance de beauté.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. La posture de l'expert</h2><p>Ne parlez pas à votre client à travers le miroir. Asseyez-vous à sa hauteur pour créer un lien de confiance direct.</p></section>`,
    coach_tip: "Écoutez deux fois plus que vous ne parlez pendant le diagnostic.",
    strategic_mantra: "Le client n'achète pas vos outils, il achète votre regard d'expert.",
    quiz_questions: [{ question: "Quelle est la meilleure position pour un diagnostic ?", options: ["Debout derrière le client", "Assis à sa hauteur", "Au bac à shampoing"], correctAnswer: 1, explanation: "Le contact visuel direct à la même hauteur crée la confiance." }],
    exercises: ["Réaliser 3 diagnostics en étant assis face au client."],
    tips: ["Observez la forme du visage et la texture du cheveu."]
  },
  {
    id: "mod_hygiene",
    topic: "Hygiène",
    title: "Propreté irréprochable : le standard luxe",
    description: "L'hygiène est votre meilleur argument de vente. Apprenez à en faire un rituel visible par vos clients.",
    mini_course: "Un salon propre est un salon qui respecte ses clients et qui peut facturer plus cher.",
    price: 500,
    aiCredits: 2,
    lesson_content: `<section class="lesson-card"><h2>I. La désinfection visible</h2><p>Désinfectez vos outils devant le client. C'est un acte de marketing autant que de santé.</p></section>`,
    coach_tip: "Un bac à shampoing mal nettoyé fait fuir les meilleurs clients définitivement.",
    strategic_mantra: "L'excellence commence par un peigne sans cheveux.",
    quiz_questions: [{ question: "Quand faut-il nettoyer ses outils ?", options: ["Le soir après la fermeture", "Une fois par semaine", "Devant chaque client"], correctAnswer: 2, explanation: "La visibilité de la propreté rassure immédiatement le client." }],
    exercises: ["Mettre en place une fiche de contrôle hygiène quotidienne."],
    tips: ["Changez de serviette après chaque client, sans exception."]
  },
  {
    id: "mod_stock",
    topic: "Gestion",
    title: "Gestion des stocks : éviter les pertes",
    description: "Ne laissez plus votre argent dormir sur les étagères. Apprenez à commander juste ce qu'il faut.",
    mini_course: "Un tube de couleur périmé, c'est un billet de banque que vous jetez.",
    price: 500,
    aiCredits: 2,
    lesson_content: `<section class="lesson-card"><h2>I. L'inventaire hebdomadaire</h2><p>Fixez un jour de la semaine pour compter vos produits. La régularité évite les achats de dernière minute trop chers.</p></section>`,
    coach_tip: "Pesez vos bols de préparation. Le surplus jeté tue votre bénéfice.",
    strategic_mantra: "Vos étagères sont des comptes bancaires de produits.",
    quiz_questions: [{ question: "Quelle est la fréquence idéale d'inventaire ?", options: ["Tous les mois", "Toutes les semaines", "Une fois par an"], correctAnswer: 1, explanation: "Un suivi hebdomadaire permet de réagir avant la rupture." }],
    exercises: ["Créer un cahier de suivi des entrées et sorties de produits."],
    tips: ["Utilisez les produits les plus anciens en premier."]
  },
  {
    id: "mod_social_media",
    topic: "Visibilité",
    title: "Réseaux sociaux : attirer des nouveaux clients",
    description: "Maîtrisez Facebook, Instagram et TikTok pour remplir votre salon sans payer de publicité.",
    mini_course: "Votre page est le premier salon que vos clients visitent virtuellement.",
    price: 500,
    aiCredits: 4,
    lesson_content: `<section class="lesson-card"><h2>I. La photo qui vend</h2><p>La lumière naturelle est votre meilleure amie. Prenez vos photos face à la fenêtre pour montrer la vraie couleur.</p></section>`,
    coach_tip: "Une vidéo « Avant/Après » réussie vaut plus que mille mots.",
    strategic_mantra: "Si vous n'êtes pas sur leur téléphone, vous n'existez pas.",
    quiz_questions: [{ question: "Où prendre la meilleure photo au salon ?", options: ["Sous les néons jaunes", "Face à la lumière du jour", "Avec le flash dans le noir"], correctAnswer: 1, explanation: "La lumière du jour respecte les reflets de votre travail." }],
    exercises: ["Publier une vidéo « Avant/Après » cette semaine."],
    tips: ["Répondez à chaque commentaire poliment."]
  },
  {
    id: "mod_fidelisation",
    topic: "Vente",
    title: "Fidélisation : faire revenir vos clients",
    description: "Apprenez à utiliser votre carnet client pour que vos clientes reviennent 8 fois par an au lieu de 4.",
    mini_course: "Garder un client coûte 5 fois moins cher qu'en trouver un nouveau.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. La relance stratégique</h2><p>Un client qui n'est pas revenu après 3 mois doit recevoir un petit message amical.</p></section>`,
    coach_tip: "Notez les préférences de vos clientes. Se souvenir de son thé préféré crée l'émotion.",
    strategic_mantra: "Un client fidèle est votre meilleur ambassadeur.",
    quiz_questions: [{ question: "Quand faut-il relancer un client absent ?", options: ["Après 1 mois", "Après 3 mois", "Après 1 an"], correctAnswer: 1, explanation: "C'est le cycle moyen de renouvellement des prestations techniques." }],
    exercises: ["Envoyer 10 messages de relance personnalisés cette semaine."],
    tips: ["Proposez le prochain rendez-vous dès la fin de la prestation actuelle."]
  },
  {
    id: "mod_management",
    topic: "Direction",
    title: "Direction d'équipe : motiver pour gagner",
    description: "Passez du rôle de patron à celui de leader. Apprenez à inspirer votre équipe pour qu'elle produise plus.",
    mini_course: "Votre équipe traitera vos clients comme vous traitez votre équipe.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. Le briefing du matin</h2><p>Passez 5 minutes chaque matin avec votre équipe pour fixer les objectifs et l'ambiance de la journée.</p></section>`,
    coach_tip: "Félicitez vos employés devant tout le monde, recadrez-les en tête-à-tête.",
    strategic_mantra: "Seul on va vite, ensemble on construit un empire.",
    quiz_questions: [{ question: "Quel est le meilleur moment pour motiver son équipe ?", options: ["Le soir en partant", "Le matin avant le premier client", "Pendant la pause déjeuner"], correctAnswer: 1, explanation: "Le matin lance l'énergie positive pour toute la journée." }],
    exercises: ["Organiser un entretien de 15 minutes avec chaque employé cette semaine."],
    tips: ["Écoutez les idées de vos collaborateurs."]
  },
  {
    id: "mod_tarification",
    topic: "Gestion",
    title: "Tarifs et rentabilité : fixer le juste prix",
    description: "Apprenez à calculer vos prix en fonction de vos charges réelles, pas en fonction du voisin.",
    mini_course: "Le chiffre d'affaires flatte l'ego, le bénéfice nourrit la famille.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. Le coût à la minute</h2><p>Chaque minute passée au salon a un coût (loyer, électricité, salaires). Apprenez à le calculer.</p></section>`,
    coach_tip: "Si vous bradez vos prix, vous bradez votre talent et votre avenir.",
    strategic_mantra: "On ne gère bien que ce que l'on mesure.",
    quiz_questions: [{ question: "Comment fixer un nouveau prix ?", options: ["Regarder les prix du quartier", "Calculer ses charges plus sa marge", "Demander l'avis des clients"], correctAnswer: 1, explanation: "C'est la seule méthode mathématique qui garantit votre salaire." }],
    exercises: ["Calculer le coût total de fonctionnement du salon par heure."],
    tips: ["Affichez vos prix clairement à l'entrée."]
  },
  {
    id: "mod_upselling",
    topic: "Vente",
    title: "Vente additionnelle : augmenter le panier moyen",
    description: "Apprenez à proposer systématiquement le soin ou le massage dont votre client a besoin.",
    mini_course: "Proposer n'est pas forcer. C'est apporter une solution complète au client.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. La recommandation d'expert</h2><p>Ne demandez pas « Voulez-vous un soin ? », dites « Pour protéger vos mèches, je vous conseille ce soin profond ».</p></section>`,
    coach_tip: "Un soin offert au bac aujourd'hui est une vente de soin garantie pour demain.",
    strategic_mantra: "Le meilleur moment pour proposer est quand le client est détendu au bac.",
    quiz_questions: [{ question: "Quelle phrase fait vendre le mieux ?", options: ["Vous voulez un soin ?", "Pour vos pointes abîmées, je préconise ce rituel", "Rien d'autre ?"], correctAnswer: 1, explanation: "L'expert préconise une solution au lieu de poser une question fermée." }],
    exercises: ["Réussir 5 ventes de services additionnels en une journée."],
    tips: ["Expliquez toujours le bénéfice pour le client."]
  },
  {
    id: "mod_retail",
    topic: "Vente",
    title: "Vente de produits : prolonger l'expertise à la maison",
    description: "Apprenez à vendre les produits de votre boutique pour augmenter vos revenus sans temps de travail supplémentaire.",
    mini_course: "Si votre client achète son shampoing au supermarché, vous perdez de l'argent.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. La prescription</h2><p>Expliquez chaque produit que vous utilisez pendant que vous le faites. Le client doit savoir pourquoi c'est bon pour lui.</p></section>`,
    coach_tip: "Vos bacs à shampoing sont votre meilleure salle d'exposition de produits.",
    strategic_mantra: "Vendre un produit, c'est prendre soin du client jusque dans sa douche.",
    quiz_questions: [{ question: "Quand faut-il parler des produits ?", options: ["À la caisse au moment de payer", "Pendant toute la prestation", "Uniquement si le client demande"], correctAnswer: 1, explanation: "L'éducation du client se fait par étape pendant qu'il teste le produit." }],
    exercises: ["Vendre au moins un produit à 3 clientes consécutives."],
    tips: ["Faites sentir les textures et les parfums."]
  },
  {
    id: "mod_ergonomie",
    topic: "Organisation",
    title: "Organisation du salon : efficacité maximale",
    description: "Gagnez du temps et fatiguez-vous moins en organisant votre poste de travail comme un cockpit d'avion.",
    mini_course: "Chaque pas inutile est une seconde de profit perdue.",
    price: 500,
    aiCredits: 2,
    lesson_content: `<section class="lesson-card"><h2>I. Le rayon d'action</h2><p>Tout ce dont vous avez besoin pour travailler doit être accessible sans que vous ayez à bouger vos pieds.</p></section>`,
    coach_tip: "Un poste de travail bien rangé réduit votre stress et celui de votre client.",
    strategic_mantra: "Moins vous bougez vos pieds, plus vos mains produisent de la valeur.",
    quiz_questions: [{ question: "Où doivent être vos outils principaux ?", options: ["Sur une étagère au fond", "Dans un rayon de 60 cm autour de vous", "Dans le placard fermé"], correctAnswer: 1, explanation: "C'est la zone d'efficacité maximale pour éviter la fatigue." }],
    exercises: ["Réorganiser sa desserte de travail pour ne plus avoir à se déplacer inutilement."],
    tips: ["Utilisez des dessertes à roulettes de qualité."]
  },
  {
    id: "mod_image_pro",
    topic: "Image",
    title: "Image professionnelle : incarner la réussite",
    description: "Votre apparence et celle de votre équipe déterminent la valeur de vos tarifs aux yeux du client.",
    mini_course: "On ne peut pas vendre de l'élégance en portant des vêtements négligés.",
    price: 500,
    aiCredits: 2,
    lesson_content: `<section class="lesson-card"><h2>I. L'uniforme du succès</h2><p>Une tenue harmonieuse et propre pour toute l'équipe renforce instantanément votre professionnalisme.</p></section>`,
    coach_tip: "Regardez vos chaussures. Les clientes les remarquent quand elles sont allongées au bac.",
    strategic_mantra: "Vous êtes votre première publicité.",
    quiz_questions: [{ question: "Pourquoi imposer un code vestimentaire ?", options: ["Pour faire joli", "Pour justifier des tarifs haut de gamme", "Parce que c'est la règle"], correctAnswer: 1, explanation: "L'image de l'équipe fixe la valeur perçue de la prestation." }],
    exercises: ["Définir une tenue commune (couleur ou uniforme) pour tout le salon."],
    tips: ["Portez un badge avec votre prénom."]
  },
  {
    id: "mod_tresorerie",
    topic: "Gestion",
    title: "Gestion de la caisse : ne plus jamais être à sec",
    description: "Apprenez à gérer vos entrées et sorties d'argent au quotidien pour anticiper vos factures.",
    mini_course: "L'argent de la caisse n'est pas votre argent de poche personnel.",
    price: 500,
    aiCredits: 2,
    lesson_content: `<section class="lesson-card"><h2>I. La règle d'or</h2><p>Séparez physiquement l'argent destiné aux charges (loyer, factures, produits) de votre propre salaire.</p></section>`,
    coach_tip: "Mettez de côté votre loyer et vos taxes un peu chaque jour.",
    strategic_mantra: "La caisse est le cœur du salon, si elle s'arrête, tout s'arrête.",
    quiz_questions: [{ question: "Que faire de la recette du jour ?", options: ["Payer ses courses personnelles", "La déposer sur le compte professionnel du salon", "La garder dans le tiroir sans compter"], correctAnswer: 1, explanation: "La rigueur bancaire est le début de la richesse." }],
    exercises: ["Vérifier le solde de sa caisse chaque matin avant l'ouverture."],
    tips: ["Utilisez un petit cahier de caisse pour chaque dépense, même minime."]
  },
  {
    id: "mod_litiges",
    topic: "Relation client",
    title: "Clients difficiles : transformer un problème en succès",
    description: "Apprenez à gérer les réclamations et les mécontentements avec le sourire et professionnalisme.",
    mini_course: "Une plainte bien gérée crée un client fidèle pour la vie.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. La méthode du calme</h2><p>N'essayez jamais de vous justifier immédiatement. Écoutez le client jusqu'au bout sans l'interrompre.</p></section>`,
    coach_tip: "Un client qui se plaint est un client qui vous donne une chance de vous améliorer.",
    strategic_mantra: "Le client mécontent veut surtout être entendu.",
    quiz_questions: [{ question: "Quelle est la première chose à faire face à une réclamation ?", options: ["Expliquer pourquoi il a tort", "Écouter en restant calme", "Lui demander de partir"], correctAnswer: 1, explanation: "L'écoute active désamorce 80 % des conflits." }],
    exercises: ["S'entraîner à répondre calmement à une critique imaginaire."],
    tips: ["Cherchez toujours une solution « gagnant-gagnant »."]
  },
  {
    id: "mod_booking",
    topic: "Visibilité",
    title: "Réservation digitale : le salon ouvert 24h/24",
    description: "Mettez en place la prise de rendez-vous automatique pour ne plus rater d'appels quand vous travaillez.",
    mini_course: "Beaucoup de clientes veulent réserver le soir quand vous dormez.",
    price: 500,
    aiCredits: 2,
    lesson_content: `<section class="lesson-card"><h2>I. L'automatisation</h2><p>Laissez vos clientes prendre rendez-vous via WhatsApp ou une application simple pour vous libérer du temps.</p></section>`,
    coach_tip: "Un rappel automatique par message réduit les rendez-vous oubliés de 70 %.",
    strategic_mantra: "Gagnez du temps pour ce qui compte : la beauté.",
    quiz_questions: [{ question: "Pourquoi automatiser ses rendez-vous ?", options: ["Pour faire moderne", "Pour ne plus rater de clients le soir", "Pour ne plus parler aux gens"], correctAnswer: 1, explanation: "Cela permet de capter les clients au moment où ils y pensent, même la nuit." }],
    exercises: ["Tester un lien de réservation simple sur son profil WhatsApp."],
    tips: ["Mettez votre lien de réservation sur Facebook."]
  },
  {
    id: "mod_parrainage",
    topic: "Vente",
    title: "Cercle de recommandation : le bouche-à-oreille",
    description: "Transformez vos clientes actuelles en une équipe de vente qui vous ramène leurs amies.",
    mini_course: "Vos meilleures clientes connaissent vos futurs meilleures clientes.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. Le cadeau de parrainage</h2><p>Offrez un avantage (un soin ou une remise) à la cliente qui vous ramène une amie, et à l'amie aussi !</p></section>`,
    coach_tip: "Le parrainage fonctionne mieux quand la récompense est un service de beauté plutôt que de l'argent.",
    strategic_mantra: "Le bouche-à-oreille se cultive avec générosité.",
    quiz_questions: [{ question: "À qui proposer de parrainer ?", options: ["À tout le monde sans distinction", "Uniquement à vos clientes les plus satisfaites", "À personne, c'est gênant"], correctAnswer: 1, explanation: "Vos clients satisfaits sont les seuls capables de bien vous vendre." }],
    exercises: ["Lancer son offre de parrainage."],
    tips: ["Remerciez toujours chaleureusement la personne qui vous a recommandé."]
  }
];

export const BADGES: Badge[] = [
  {
    id: "first_module",
    name: "Décollage",
    icon: "🚀",
    description: "Premier module terminé avec succès.",
    condition: (u, mods) => mods.some(m => m.status === ModuleStatus.COMPLETED)
  },
  {
    id: "dedicated",
    name: "Maître du salon",
    icon: "🏆",
    description: "5 modules terminés.",
    condition: (u, mods) => mods.filter(m => m.status === ModuleStatus.COMPLETED).length >= 5
  }
];

export const DIAGNOSTIC_QUESTIONS = [
  { id: 1, text: "Votre équipe est-elle formée aux techniques d'un bon accueil téléphonique ?", category: "Accueil", linkedModuleId: "mod_accueil_tel" },
  { id: 2, text: "L'équipe s'entraîne-t-elle à faire un bon diagnostic avant chaque prestation ?", category: "Technique", linkedModuleId: "mod_diagnostic" },
  { id: 3, text: "Les protocoles d'hygiène sont-ils affichés et respectés scrupuleusement par tous ?", category: "Hygiène", linkedModuleId: "mod_hygiene" },
  { id: 4, text: "Avez-vous un inventaire à jour chaque semaine pour éviter les ruptures de stock ?", category: "Gestion", linkedModuleId: "mod_stock" },
  { id: 5, text: "Publiez-vous régulièrement (au moins 3 fois par semaine) sur vos réseaux sociaux ?", category: "Visibilité", linkedModuleId: "mod_social_media" },
  { id: 6, text: "Utilisez-vous un fichier client pour relancer ceux qui ne sont plus venus depuis 3 mois ?", category: "Vente", linkedModuleId: "mod_fidelisation" },
  { id: 7, text: "Réalisez-vous des entretiens individuels de motivation avec vos employés chaque mois ?", category: "Direction", linkedModuleId: "mod_management" },
  { id: 8, text: "Connaissez-vous précisément votre coût à la minute pour fixer vos tarifs ?", category: "Gestion", linkedModuleId: "mod_tarification" },
  { id: 9, text: "Proposez-vous systématiquement un service additionnel (soin, massage) à chaque client ?", category: "Vente", linkedModuleId: "mod_upselling" },
  { id: 10, text: "Votre taux de revente de produits représente-t-il plus de 15 % de votre chiffre d'affaires ?", category: "Vente", linkedModuleId: "mod_retail" },
  { id: 11, text: "L'organisation de vos postes de travail est-elle optimisée pour éviter les pas inutiles ?", category: "Organisation", linkedModuleId: "mod_ergonomie" },
  { id: 12, text: "L'équipe porte-t-elle une tenue professionnelle harmonieuse reflétant l'image du salon ?", category: "Image", linkedModuleId: "mod_image_pro" },
  { id: 13, text: "Suivez-vous quotidiennement vos entrées/sorties d'argent sur un tableau de bord ?", category: "Gestion", linkedModuleId: "mod_tresorerie" },
  { id: 14, text: "Avez-vous une procédure écrite pour gérer calmement les réclamations clients ?", category: "Relation client", linkedModuleId: "mod_litiges" },
  { id: 15, text: "Vos clients peuvent-ils réserver leur prestation en ligne 24h/24 et 7j/7 ?", category: "Visibilité", linkedModuleId: "mod_booking" },
  { id: 16, text: "Avez-vous un système de parrainage actif pour attirer de nouveaux clients ?", category: "Vente", linkedModuleId: "mod_parrainage" }
];
