import { TrainingModule, Badge, ModuleStatus } from './types';

// Identité visuelle de Coach Kita
export const COACH_KITA_AVATAR = "https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=400&q=80";

// Numéro réservé pour l'accès Super Admin (Format international)
export const SUPER_ADMIN_PHONE_NUMBER = "+2250001020304";

export const TRAINING_CATALOG: TrainingModule[] = [
  {
    id: "mod_accueil_tel",
    topic: "Accueil",
    title: "L'excellence de l'accueil téléphonique",
    description: "La première impression se joue souvent au téléphone. Apprenez à décrocher, sourire et gérer les attentes.",
    mini_course: "Transformez chaque appel en rendez-vous.",
    price: 500,
    aiCredits: 3,
    lesson_content: "<h2>Le téléphone : votre porte d'entrée</h2><p>Le sourire s'entend au téléphone. Décrochez avant la 3ème sonnerie et utilisez une phrase d'accueil standardisée.</p>",
    coach_tip: "Installe un petit miroir devant le téléphone pour te voir sourire en parlant.",
    strategic_mantra: "Un appel perdu est un client qui part chez la concurrence.",
    quiz_questions: [{ question: "Quand décrocher ?", options: ["Après 5 sonneries", "Avant la 3ème sonnerie", "Quand on a le temps"], correctAnswer: 1, explanation: "La rapidité montre votre professionnalisme." }],
    exercises: ["Simuler 3 appels difficiles."],
    tips: ["Souriez en parlant."]
  },
  {
    id: "mod_diagnostic",
    topic: "Vente",
    title: "Le Diagnostic Technique Expert",
    description: "Apprenez à analyser avant d'agir pour valoriser votre expertise.",
    mini_course: "La clé pour augmenter votre panier moyen.",
    price: 500,
    aiCredits: 3,
    lesson_content: "<h2>Écouter avant de toucher</h2><p>Le diagnostic est le moment où vous montrez votre expertise. Posez des questions ouvertes.</p>",
    coach_tip: "Interdiction de toucher les cheveux avant d'avoir posé 3 questions clés.",
    strategic_mantra: "Le client achète votre solution, pas seulement votre temps.",
    quiz_questions: [{ question: "Pourquoi reformuler ?", options: ["Pour perdre du temps", "Pour valider le besoin", "Pour faire joli"], correctAnswer: 1, explanation: "La reformulation évite les déceptions post-prestation." }],
    exercises: ["Pratiquer la méthode des questions ouvertes."],
    tips: ["Asseyez-vous à la hauteur du client."]
  },
  {
    id: "mod_hygiene",
    topic: "Hygiène",
    title: "Protocoles d'Hygiène & Sécurité",
    description: "Faites de la propreté votre meilleur argument marketing.",
    mini_course: "Rassurez vos clients par une rigueur exemplaire.",
    price: 500,
    aiCredits: 2,
    lesson_content: "<h2>La confiance passe par le bac</h2><p>Désinfectez vos outils devant le client. La propreté doit être visible.</p>",
    coach_tip: "Laisse une lingette désinfectante bien en vue sur chaque poste.",
    strategic_mantra: "Un salon sale est un salon qui meurt.",
    quiz_questions: [{ question: "Où désinfecter ?", options: ["En réserve", "Devant le client", "Le soir uniquement"], correctAnswer: 1, explanation: "Le client doit voir que vous prenez soin de sa santé." }],
    exercises: ["Créer une check-list de nettoyage horaire."],
    tips: ["Videz les poubelles régulièrement."]
  },
  {
    id: "mod_stock",
    topic: "Gestion",
    title: "Optimisation des Stocks",
    description: "Ne laissez plus votre argent dormir sur les étagères.",
    mini_course: "Gérez vos produits comme un pro.",
    price: 500,
    aiCredits: 2,
    lesson_content: "<h2>L'inventaire tournant</h2><p>Évitez les ruptures et les surstockages. Suivez vos consommations bac avec précision.</p>",
    coach_tip: "Fais l'inventaire de tes 5 produits les plus vendus chaque lundi matin.",
    strategic_mantra: "Le stock, c'est de l'argent liquide qui prend la poussière.",
    quiz_questions: [{ question: "Fréquence d'inventaire ?", options: ["Par an", "Par mois/semaine", "Jamais"], correctAnswer: 1, explanation: "Un suivi régulier permet d'optimiser la trésorerie." }],
    exercises: ["Calculer le coût de consommation moyen d'une couleur."],
    tips: ["Utilisez la méthode PEPS (Premier Entré, Premier Sorti)."]
  },
  {
    id: "mod_social_media",
    topic: "Digital",
    title: "Rayonner sur les Réseaux Sociaux",
    description: "Attirez de nouveaux clients grâce à Instagram et Facebook.",
    mini_course: "Créez du contenu qui donne envie.",
    price: 500,
    aiCredits: 5,
    lesson_content: "<h2>Le 'Avant/Après' : votre meilleure pub</h2><p>La lumière est primordiale. Photographiez vos plus belles réalisations tous les jours.</p>",
    coach_tip: "Achète un anneau lumineux (Ring Light) pour tes photos.",
    strategic_mantra: "Si vous n'êtes pas sur le téléphone de vos clients, vous n'existez pas.",
    quiz_questions: [{ question: "Fréquence de post ?", options: ["1/mois", "3/semaine minimum", "Quand j'y pense"], correctAnswer: 1, explanation: "L'algorithme privilégie la régularité." }],
    exercises: ["Prendre 3 photos 'Avant/Après' aujourd'hui."],
    tips: ["Utilisez des hashtags locaux."]
  },
  {
    id: "mod_fidelisation",
    topic: "Vente",
    title: "Fidélisation : Faire revenir le client",
    description: "Il coûte 5 fois moins cher de garder un client que d'en trouver un nouveau.",
    mini_course: "Le secret des agendas remplis.",
    price: 500,
    aiCredits: 3,
    lesson_content: "<h2>Le fichier client : votre mine d'or</h2><p>Notez tout : anniversaires, préférences, historique technique. Relancez les inactifs.</p>",
    coach_tip: "Propose le prochain RDV dès l'encaissement, pas quand le client part.",
    strategic_mantra: "Un client fidèle est un ambassadeur gratuit.",
    quiz_questions: [{ question: "Quand proposer le prochain RDV ?", options: ["À l'encaissement", "Par SMS plus tard", "Jamais"], correctAnswer: 0, explanation: "C'est le moment où le client est le plus satisfait." }],
    exercises: ["Appeler 5 clients qui ne sont pas venus depuis 3 mois."],
    tips: ["Offrez une petite attention pour l'anniversaire."]
  },
  {
    id: "mod_management",
    topic: "Management",
    title: "Le Leader Inspirant",
    description: "Motivez votre équipe pour atteindre l'excellence collective.",
    mini_course: "Gérez les humains, pas seulement les plannings.",
    price: 500,
    aiCredits: 4,
    lesson_content: "<h2>Réunions individuelles (One-to-One)</h2><p>Écoutez les besoins de vos collaborateurs. Fixez des objectifs clairs et atteignables.</p>",
    coach_tip: "Remercie chaque employé pour un travail bien fait avant qu'il ne parte le soir.",
    strategic_mantra: "Une équipe motivée décuple le chiffre d'affaires.",
    quiz_questions: [{ question: "Fréquence des points individuels ?", options: ["Par an", "Chaque mois", "Jamais"], correctAnswer: 1, explanation: "Un suivi mensuel maintient la motivation." }],
    exercises: ["Organiser un café d'équipe de 15 min demain matin."],
    tips: ["Déléguez les tâches simples."]
  },
  {
    id: "mod_tarification",
    topic: "Gestion",
    title: "Prix & Rentabilité",
    description: "Calculez vos tarifs pour dégager un vrai salaire.",
    mini_course: "Ne bradez plus votre talent.",
    price: 500,
    aiCredits: 3,
    lesson_content: "<h2>Le coût à la minute</h2><p>Connaissez vos charges fixes. Votre tarif doit couvrir vos frais, votre salaire et votre marge.</p>",
    coach_tip: "Compare tes prix avec ceux du quartier et ajuste si tu es trop bas.",
    strategic_mantra: "Vendre à perte, c'est travailler pour la gloire.",
    quiz_questions: [{ question: "Faut-il baisser les prix en crise ?", options: ["Oui pour attirer", "Non, valoriser le service", "Peut-être"], correctAnswer: 1, explanation: "Baisser les prix dévalorise votre image." }],
    exercises: ["Calculer le coût d'une heure d'ouverture du salon."],
    tips: ["Affichez clairement vos tarifs."]
  },
  {
    id: "mod_upselling",
    topic: "Vente",
    title: "Vente Additionnelle & Services",
    description: "Augmentez votre ticket moyen sans forcer.",
    mini_course: "Proposez le 'petit plus' qui fait la différence.",
    price: 500,
    aiCredits: 2,
    lesson_content: "<h2>Le 'Up-selling' bienveillant</h2><p>Proposez toujours un soin complémentaire cohérent avec la prestation de base.</p>",
    coach_tip: "Ne dis pas 'Voulez-vous un soin ?', dis 'Je vous conseille ce soin pour protéger votre couleur'.",
    strategic_mantra: "Le silence est le pire ennemi de votre chiffre d'affaires.",
    quiz_questions: [{ question: "Comment proposer un soin ?", options: ["Par le bénéfice client", "Par le prix", "En insistant"], correctAnswer: 0, explanation: "Le client achète un résultat (brillance, douceur)." }],
    exercises: ["Ajouter un soin à 20% des tickets de la journée."],
    tips: ["Montrez les produits utilisés."]
  },
  {
    id: "mod_retail",
    topic: "Vente",
    title: "Expertise Revente Produits",
    description: "Faites de la revente votre second moteur de croissance.",
    mini_course: "Conseillez les produits pour la maison.",
    price: 500,
    aiCredits: 3,
    lesson_content: "<h2>L'ordonnance beauté</h2><p>Le travail continue à la maison. Donnez une ordonnance écrite des produits recommandés.</p>",
    coach_tip: "Place le produit dont tu parles directement dans les mains de la cliente.",
    strategic_mantra: "Un client qui repart sans produit est un client à moitié servi.",
    quiz_questions: [{ question: "Quand parler des produits ?", options: ["À la fin", "Pendant toute la prestation", "Jamais"], correctAnswer: 1, explanation: "Le conseil doit être continu." }],
    exercises: ["Réaliser 3 ventes de produits de soin aujourd'hui."],
    tips: ["Créez un coin boutique attractif."]
  },
  {
    id: "mod_ergonomie",
    topic: "Organisation",
    title: "Ergonomie & Gain de temps",
    description: "Optimisez votre espace pour moins de fatigue et plus de clients.",
    mini_course: "Travaillez mieux, pas plus.",
    price: 500,
    aiCredits: 2,
    lesson_content: "<h2>L'organisation des postes</h2><p>Chaque outil doit avoir sa place. Réduisez les déplacements inutiles entre le bac et le poste.</p>",
    coach_tip: "Range ton matériel après chaque client, ne laisse rien traîner.",
    strategic_mantra: "L'ordre est le premier pas vers la rapidité.",
    quiz_questions: [{ question: "Pourquoi ranger ?", options: ["Pour faire beau", "Pour gagner du temps", "Pour le patron"], correctAnswer: 1, explanation: "Le désordre génère du stress et de la perte de temps." }],
    exercises: ["Réorganiser le tiroir de votre poste principal."],
    tips: ["Investissez dans du bon matériel."]
  },
  {
    id: "mod_image_pro",
    topic: "Accueil",
    title: "L'Image Professionnelle de l'Équipe",
    description: "Votre apparence est votre première publicité.",
    mini_course: "Incarnez l'excellence que vous vendez.",
    price: 500,
    aiCredits: 1,
    lesson_content: "<h2>L'uniformité et le soin</h2><p>Tenue soignée, coiffure impeccable. Vous êtes des experts de la beauté, montrez-le.</p>",
    coach_tip: "Vérifie ton apparence dans le miroir avant l'arrivée du premier client.",
    strategic_mantra: "On ne peut pas vendre de la beauté si on ne l'incarne pas.",
    quiz_questions: [{ question: "Tenue idéale ?", options: ["Jean basket", "Professionnelle et sobre", "Pyjama"], correctAnswer: 1, explanation: "L'image renforce la crédibilité." }],
    exercises: ["Définir un code couleur pour l'équipe (ex: Noir & Or)."],
    tips: ["Portez des chaussures confortables mais élégantes."]
  },
  {
    id: "mod_tresorerie",
    topic: "Gestion",
    title: "Maîtrise de la Trésorerie",
    description: "Suivez votre argent pour dormir sur vos deux oreilles.",
    mini_course: "Le pilotage financier simplifié.",
    price: 500,
    aiCredits: 4,
    lesson_content: "<h2>Le tableau de bord quotidien</h2><p>Notez vos recettes et vos d\u00e9penses. Anticipez les charges \u00e0 venir (loyer, salaires, taxes).</p>",
    coach_tip: "Ouvre un compte bancaire séparé pour tes économies de charges.",
    strategic_mantra: "Le chiffre d'affaires est une vanité, le bénéfice est une réalité.",
    quiz_questions: [{ question: "Qu'est-ce que le cash-flow ?", options: ["Le CA total", "L'argent disponible", "Les dettes"], correctAnswer: 1, explanation: "C'est l'oxygène de votre entreprise." }],
    exercises: ["Lister toutes les charges fixes du mois prochain."],
    tips: ["Gardez 3 mois de charges d'avance."]
  },
  {
    id: "mod_litiges",
    topic: "Accueil",
    title: "Gestion des Litiges Clients",
    description: "Transformez un client mécontent en fan absolu.",
    mini_course: "Désamorcez les conflits avec calme.",
    price: 500,
    aiCredits: 3,
    lesson_content: "<h2>La méthode de l'écoute active</h2><p>Ne vous justifiez pas immédiatement. Écoutez, excusez-vous et proposez une solution concrète.</p>",
    coach_tip: "Ne discute jamais un litige devant les autres clients. Isole-toi.",
    strategic_mantra: "Une plainte est un cadeau pour s'améliorer.",
    quiz_questions: [{ question: "Première étape du litige ?", options: ["S'énerver", "Écouter sans couper", "Rembourser"], correctAnswer: 1, explanation: "L'écoute calme 80% des tensions." }],
    exercises: ["Rédiger une phrase type pour répondre à un avis Google négatif."],
    tips: ["Gardez votre sang-froid."]
  },
  {
    id: "mod_booking",
    topic: "Digital",
    title: "La Réservation en Ligne",
    description: "Remplissez votre agenda même quand vous dormez.",
    mini_course: "Modernisez votre prise de rendez-vous.",
    price: 500,
    aiCredits: 2,
    lesson_content: "<h2>Disponibilité 24h/24</h2><p>60% des réservations se font en dehors des heures d'ouverture. Ne passez pas à côté.</p>",
    coach_tip: "Ajoute un bouton 'Réserver' sur ta page Instagram.",
    strategic_mantra: "Le téléphone qui sonne en pleine coupe est un ennemi de la qualité.",
    quiz_questions: [{ question: "Avantage du booking en ligne ?", options: ["Moins d'appels", "Plus de clients", "Les deux"], correctAnswer: 2, explanation: "Cela libère du temps et augmente les ventes." }],
    exercises: ["Tester un outil de réservation en ligne gratuit pendant 15 jours."],
    tips: ["Demandez un acompte pour éviter les lapins."]
  },
  {
    id: "mod_parrainage",
    topic: "Vente",
    title: "Système de Parrainage Gagnant",
    description: "Faites de vos clients vos meilleurs commerciaux.",
    mini_course: "Le bouche-à-oreille organisé.",
    price: 500,
    aiCredits: 3,
    lesson_content: "<h2>L'offre parrain/filleul</h2><p>Récompensez celui qui recommande et celui qui découvre. C'est du marketing puissant.</p>",
    coach_tip: "Donne 3 cartes de visite à tes meilleures clientes pour qu'elles les distribuent.",
    strategic_mantra: "La recommandation est le mode de recrutement le plus rentable.",
    quiz_questions: [{ question: "Qui parrainer ?", options: ["Tout le monde", "Les clients mécontents", "Les nouveaux uniquement"], correctAnswer: 0, explanation: "Tout client satisfait peut parrainer." }],
    exercises: ["Créer une offre : -20% pour le parrain et le filleul."],
    tips: ["Suivez les résultats avec un petit carnet."]
  }
];

export const BADGES: Badge[] = [
  {
    id: "first_module",
    name: "Premier pas",
    icon: "🚀",
    description: "Premier module terminé.",
    condition: (u, mods) => mods.some(m => m.status === ModuleStatus.COMPLETED)
  },
  {
    id: "dedicated",
    name: "Déterminé",
    icon: "🏆",
    description: "5 modules terminés.",
    condition: (u, mods) => mods.filter(m => m.status === ModuleStatus.COMPLETED).length >= 5
  }
];

export const DIAGNOSTIC_QUESTIONS = [
  { id: 1, text: "Votre équipe est-elle formée aux techniques d'un bon accueil téléphonique ?", category: "Accueil", linkedModuleId: "mod_accueil_tel" },
  { id: 2, text: "L'équipe s'entraîne-t-elle à faire un bon diagnostic avant chaque prestation ?", category: "Technique", linkedModuleId: "mod_diagnostic" },
  { id: 3, text: "Les protocoles d'hygiène sont-ils affichés et respectés scrupuleusement par tous ?", category: "Hygiène", linkedModuleId: "mod_hygiene" },
  { id: 4, text: "Avez-vous un inventaire à jour chaque semaine pour éviter les ruptures de stock ?", category: "Gestion", linkedModuleId: "mod_stock" },
  { id: 5, text: "Publiez-vous régulièrement (au moins 3 fois par semaine) on vos réseaux sociaux ?", category: "Digital", linkedModuleId: "mod_social_media" },
  { id: 6, text: "Utilisez-vous un fichier client pour relancer ceux qui ne sont plus venus depuis 3 mois ?", category: "Vente", linkedModuleId: "mod_fidelisation" },
  { id: 7, text: "Réalisez-vous des entretiens individuels de motivation avec vos employés chaque mois ?", category: "Management", linkedModuleId: "mod_management" },
  { id: 8, text: "Connaissez-vous précisément votre coût à la minute pour fixer vos tarifs ?", category: "Gestion", linkedModuleId: "mod_tarification" },
  { id: 9, text: "Proposez-vous systématiquement un service additionnel (soin, massage) à chaque client ?", category: "Vente", linkedModuleId: "mod_upselling" },
  { id: 10, text: "Votre taux de revente de produits représente-t-il plus de 15% de votre chiffre d'affaires ?", category: "Vente", linkedModuleId: "mod_retail" },
  { id: 11, text: "L'organisation de vos postes de travail est-elle optimisée pour éviter les pas inutiles ?", category: "Organisation", linkedModuleId: "mod_ergonomie" },
  { id: 12, text: "L'équipe porte-t-elle une tenue professionnelle harmonieuse reflétant l'image du salon ?", category: "Image", linkedModuleId: "mod_image_pro" },
  { id: 13, text: "Suivez-vous quotidiennement vos entrées/sorties d'argent sur un tableau de bord ?", category: "Gestion", linkedModuleId: "mod_tresorerie" },
  { id: 14, text: "Avez-vous une procédure écrite pour gérer calmement les réclamations clients ?", category: "Accueil", linkedModuleId: "mod_litiges" },
  { id: 15, text: "Vos clients peuvent-ils réserver leur prestation en ligne 24h/24 et 7j/7 ?", category: "Digital", linkedModuleId: "mod_booking" },
  { id: 16, text: "Avez-vous mis en place un système de parrainage actif pour attirer de nouveaux clients ?", category: "Vente", linkedModuleId: "mod_parrainage" }
];