
import { TrainingModule, Badge, ModuleStatus } from './types';

export const COACH_KITA_AVATAR = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80";
export const SUPER_ADMIN_PHONE_NUMBER = "+2250001020304";

export const TRAINING_CATALOG: TrainingModule[] = [
  {
    id: "mod_accueil_tel",
    topic: "Accueil",
    title: "L'art de l'accueil téléphonique d'élite",
    description: "Le premier contact est le moment où vous gagnez ou perdez un client. Apprenez le protocole des salons de luxe.",
    mini_course: "Votre téléphone n'est pas un outil de communication, c'est votre première caisse enregistreuse.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. La Signature Sonore</h2><p>Un expert ne répond jamais par un simple "Allô". La structure recommandée est : <strong>"Salon [Nom], [Votre Prénom] à votre écoute, bonjour"</strong>.</p></section>`,
    coach_tip: "Sourire en parlant s'entend au téléphone.",
    strategic_mantra: "Un appel mal géré est un billet de banque offert au concurrent.",
    quiz_questions: [{ question: "Quelle est la phrase d'accueil idéale ?", options: ["Allô ?", "Salon [Nom], [Prénom] à votre écoute, bonjour", "Oui c'est pourquoi ?"], correctAnswer: 1, explanation: "Cette formule établit l'autorité." }],
    exercises: ["Pratiquer la signature sur 10 appels."],
    tips: ["Restez calme."]
  },
  {
    id: "mod_diagnostic",
    topic: "Vente",
    title: "Le Diagnostic : Consultant vs Exécutant",
    description: "Apprenez à asseoir votre autorité technique pour vendre des services à haute valeur ajoutée.",
    mini_course: "Le diagnostic transforme une coupe en une ordonnance de beauté.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. La Posture d'Expert</h2><p>Asseyez-vous à hauteur d'yeux de votre client pour briser la barrière du miroir.</p></section>`,
    coach_tip: "Écoutez 80%, parlez 20%.",
    strategic_mantra: "Le client n'achète pas vos ciseaux, il achète votre regard.",
    quiz_questions: [{ question: "Où se placer pour le diagnostic ?", options: ["Derrière le fauteuil", "À hauteur d'yeux du client", "Au labo"], correctAnswer: 1, explanation: "Le contact visuel crée la confiance." }],
    exercises: ["Faire 3 diagnostics assis."],
    tips: ["Prendre des notes."]
  },
  {
    id: "mod_hygiene",
    topic: "Hygiène",
    title: "Protocoles Sanitaires : Le Standard Luxe",
    description: "L'hygiène n'est pas une option, c'est votre premier argument de réassurance client.",
    mini_course: "Un salon propre est un salon qui respecte ses clients et ses prix.",
    price: 500,
    aiCredits: 2,
    lesson_content: `<section class="lesson-card"><h2>I. La Stérilisation Visible</h2><p>Désinfectez vos outils devant le client. C'est un acte de marketing autant que d'hygiène.</p></section>`,
    coach_tip: "Un bac à shampoing sale fait fuir 40% des nouveaux clients.",
    strategic_mantra: "L'excellence commence par un peigne sans cheveux.",
    quiz_questions: [{ question: "Quand désinfecter ses outils ?", options: ["Le soir", "Une fois par semaine", "Devant chaque client"], correctAnswer: 2, explanation: "La visibilité crée la réassurance." }],
    exercises: ["Mettre en place une check-list hygiène."],
    tips: ["Changez les serviettes après chaque client."]
  },
  {
    id: "mod_stock",
    topic: "Gestion",
    title: "Gestion des Stocks : Zéro Rupture, Zéro Gaspillage",
    description: "Maîtrisez vos flux de produits pour ne jamais manquer de rien sans immobiliser trop de cash.",
    mini_course: "Un tube de couleur périmé est de l'argent jeté par la fenêtre.",
    price: 500,
    aiCredits: 2,
    lesson_content: `<section class="lesson-card"><h2>I. L'Inventaire Hebdomadaire</h2><p>Fixez un jour précis pour votre inventaire. La régularité évite les urgences coûteuses.</p></section>`,
    coach_tip: "Pesez vos bols. Le gaspillage de produit est le cancer de la marge.",
    strategic_mantra: "Vos étagères sont des comptes bancaires de produits.",
    quiz_questions: [{ question: "À quelle fréquence faire l'inventaire ?", options: ["Tous les mois", "Toutes les semaines", "Une fois par an"], correctAnswer: 1, explanation: "L'hebdomadaire permet de réagir vite." }],
    exercises: ["Créer un tableau de suivi des stocks."],
    tips: ["Premier entré, premier sorti."]
  },
  {
    id: "mod_social_media",
    topic: "Digital",
    title: "Social Media : Attirer 10 Clients par Semaine",
    description: "Dominez Instagram et TikTok pour remplir votre carnet de rendez-vous gratuitement.",
    mini_course: "Instagram est la vitrine que vos clients visitent avant de franchir votre porte.",
    price: 500,
    aiCredits: 4,
    lesson_content: `<section class="lesson-card"><h2>I. Le Avant/Après Viral</h2><p>La lumière est tout. Prenez vos photos face à la fenêtre, jamais sous un néon jaune.</p></section>`,
    coach_tip: "Un Reel par jour éloigne le salon vide pour toujours.",
    strategic_mantra: "Si vous n'êtes pas sur leur écran, vous n'existez pas.",
    quiz_questions: [{ question: "Quelle est la meilleure lumière pour une photo ?", options: ["Lumière naturelle", "Néon jaune", "Flash du téléphone"], correctAnswer: 0, explanation: "Elle respecte les couleurs techniques." }],
    exercises: ["Poster 3 Reels cette semaine."],
    tips: ["Répondez aux commentaires."]
  },
  {
    id: "mod_fidelisation",
    topic: "Vente",
    title: "Fidélisation : Faire revenir le client 8 fois par an",
    description: "Apprenez à utiliser votre fichier client pour booster votre taux de retour.",
    mini_course: "Il coûte 5 fois plus cher d'attirer un nouveau client que de garder un ancien.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. La Relance à 3 Mois</h2><p>Un client qui n'est pas revenu depuis 90 jours est un client perdu si vous n'agissez pas.</p></section>`,
    coach_tip: "Notez le nom du chien ou du mari. Le détail crée l'émotion.",
    strategic_mantra: "Un client fidèle est un ambassadeur non rémunéré.",
    quiz_questions: [{ question: "Après combien de temps relancer un client ?", options: ["6 mois", "3 mois", "1 an"], correctAnswer: 1, explanation: "C'est le cycle moyen de renouvellement." }],
    exercises: ["Relancer 10 clients cette semaine."],
    tips: ["Utilisez WhatsApp Business."]
  },
  {
    id: "mod_management",
    topic: "Management",
    title: "Leader Spirit : Motiver son équipe au quotidien",
    description: "Passez de patron à leader. Apprenez à déléguer et à inspirer.",
    mini_course: "Votre équipe traitera vos clients comme vous traitez votre équipe.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. Le Briefing du Matin</h2><p>5 minutes chaque matin pour fixer l'objectif de CA de la journée.</p></section>`,
    coach_tip: "Félicitez en public, recadrez en privé.",
    strategic_mantra: "Seul on va vite, ensemble on va loin.",
    quiz_questions: [{ question: "Quand faire le briefing ?", options: ["Le soir en partant", "Le matin avant le premier client", "Pendant la pause"], correctAnswer: 1, explanation: "Cela lance la dynamique de journée." }],
    exercises: ["Animer son premier briefing matin."],
    tips: ["Écoutez votre équipe."]
  },
  {
    id: "mod_tarification",
    topic: "Gestion",
    title: "Tarification : Calculer sa Rentabilité Minute",
    description: "Fixez vos prix sur vos coûts réels, pas sur ceux du voisin.",
    mini_course: "Le CA flatte l'ego, le bénéfice paye les factures.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. Le Coût de Revient</h2><p>L'eau, l'électricité et le loyer coûtent cher. Chaque minute passée au bac doit être facturée.</p></section>`,
    coach_tip: "Si tu n'augmentes pas tes prix de 5% par an, tu t'appauvris.",
    strategic_mantra: "Brader vos prix, c'est brader votre talent.",
    quiz_questions: [{ question: "Comment fixer un prix ?", options: ["Regarder le voisin", "Calculer ses charges + marge", "Demander au client"], correctAnswer: 1, explanation: "C'est la seule méthode mathématique." }],
    exercises: ["Calculer le coût minute du salon."],
    tips: ["Affichez vos prix clairement."]
  },
  {
    id: "mod_upselling",
    topic: "Vente",
    title: "Upselling : Booster le Panier Moyen de 20%",
    description: "Apprenez à proposer le service additionnel dont le client a besoin.",
    mini_course: "Le 'non' n'est qu'une étape vers le 'oui'. Proposez, ne vendez pas.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. Le Soin au Bac</h2><p>Ne demandez pas 'voulez-vous un soin', mais 'quel soin choisissons-nous pour vos pointes ?'.</p></section>`,
    coach_tip: "Un massage crânien offert est une vente de soin garantie demain.",
    strategic_mantra: "Le meilleur moment pour vendre est quand le client est déjà convaincu.",
    quiz_questions: [{ question: "Quelle phrase est la plus vendeuse ?", options: ["Vous voulez un soin ?", "Pour vos pointes, je recommande ce soin profond", "Rien de plus ?"], correctAnswer: 1, explanation: "C'est une recommandation d'expert." }],
    exercises: ["Réaliser 5 ventes additionnelles."],
    tips: ["Expliquez les bénéfices."]
  },
  {
    id: "mod_retail",
    topic: "Vente",
    title: "Retail Master : Vendre des produits comme un Pro",
    description: "Transformez vos bacs en zone de prescription de produits à domicile.",
    mini_course: "Le service continue dans la salle de bain du client.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. La Prescription</h2><p>Expliquez chaque produit que vous utilisez pendant la prestation.</p></section>`,
    coach_tip: "Si le client part sans produit, son brushing ne durera pas.",
    strategic_mantra: "Vendre un produit, c'est prolonger votre art.",
    quiz_questions: [{ question: "Quand parler des produits ?", options: ["À la caisse", "Pendant toute la prestation", "Jamais"], correctAnswer: 1, explanation: "L'éducation se fait en temps réel." }],
    exercises: ["Vendre 2 shampoings aujourd'hui."],
    tips: ["Faites sentir les textures."]
  },
  {
    id: "mod_ergonomie",
    topic: "Organisation",
    title: "Ergonomie : Travailler plus vite et sans douleur",
    description: "Organisez votre cockpit de travail pour une efficacité maximale.",
    mini_course: "Un gérant fatigué est un gérant moins rentable.",
    price: 500,
    aiCredits: 2,
    lesson_content: `<section class="lesson-card"><h2>I. La Zone de Proximité</h2><p>Tout doit être à moins de 60cm de vos mains.</p></section>`,
    coach_tip: "Changez de brosses souvent, vos poignets vous remercieront.",
    strategic_mantra: "L'organisation est l'amie de la vitesse.",
    quiz_questions: [{ question: "Quelle est la zone d'efficacité ?", options: ["Rayon de 60cm", "Tout le salon", "Le labo"], correctAnswer: 0, explanation: "Cela limite les pas inutiles." }],
    exercises: ["Réorganiser son poste de travail."],
    tips: ["Desserte mobile."]
  },
  {
    id: "mod_image_pro",
    topic: "Image",
    title: "Image de Marque : Incarner l'Excellence",
    description: "Votre tenue et celle de votre équipe fixent la valeur de vos tarifs.",
    mini_course: "On ne peut pas vendre du luxe en étant en jogging.",
    price: 500,
    aiCredits: 2,
    lesson_content: `<section class="lesson-card"><h2>I. L'Uniforme de Succès</h2><p>Une tenue harmonieuse renforce le sentiment de professionnalisme.</p></section>`,
    coach_tip: "Vos chaussures doivent être impeccables, les clients les regardent au bac.",
    strategic_mantra: "Soyez votre propre publicité vivante.",
    quiz_questions: [{ question: "Pourquoi une tenue pro ?", options: ["Pour avoir chaud", "Pour justifier ses tarifs luxe", "C'est obligatoire"], correctAnswer: 1, explanation: "L'image fixe la valeur perçue." }],
    exercises: ["Définir le dress code du salon."],
    tips: ["Badge avec prénom."]
  },
  {
    id: "mod_tresorerie",
    topic: "Gestion",
    title: "Trésorerie : Maîtriser son Cash-Flow",
    description: "Apprenez à séparer l'argent du salon de votre argent personnel.",
    mini_course: "La caisse du salon n'est pas votre portefeuille personnel.",
    price: 500,
    aiCredits: 2,
    lesson_content: `<section class="lesson-card"><h2>I. Les 3 Comptes</h2><p>Compte Charges, Compte Salaire, Compte Investissement.</p></section>`,
    coach_tip: "Provisionnez vos taxes chaque semaine.",
    strategic_mantra: "Le cash est le sang de votre entreprise.",
    quiz_questions: [{ question: "Que faire de la recette ?", options: ["La garder sur soi", "La déposer sur le compte pro", "Payer ses courses"], correctAnswer: 1, explanation: "La rigueur bancaire évite les faillites." }],
    exercises: ["Vérifier son solde chaque matin."],
    tips: ["Suivi quotidien."]
  },
  {
    id: "mod_litiges",
    topic: "Accueil",
    title: "Gestion des Litiges : Transformer un Mécontent en Fan",
    description: "Apprenez à gérer les réclamations avec calme et professionnalisme.",
    mini_course: "Une plainte bien gérée crée un client fidèle à vie.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. La Méthode LAST</h2><p>Listen (Écouter), Apologize (S'excuser), Solve (Résoudre), Thank (Remercier).</p></section>`,
    coach_tip: "Ne justifiez jamais, résolvez d'abord.",
    strategic_mantra: "Le client mécontent a souvent raison de s'exprimer.",
    quiz_questions: [{ question: "Quelle est la première étape d'un litige ?", options: ["S'énerver", "Écouter sans interrompre", "Rendre l'argent"], correctAnswer: 1, explanation: "L'écoute désamorce la colère." }],
    exercises: ["Jouer un sketch de litige avec l'équipe."],
    tips: ["Restez professionnel."]
  },
  {
    id: "mod_booking",
    topic: "Digital",
    title: "Booking 24/7 : Votre Salon ne dort jamais",
    description: "Mettez en place la réservation en ligne pour capter les clients de nuit.",
    mini_course: "50% des clients réservent après 20h, quand vous êtes fermé.",
    price: 500,
    aiCredits: 2,
    lesson_content: `<section class="lesson-card"><h2>I. L'Automatisation</h2><p>Gagnez 2h de temps secrétariat par jour en automatisant vos rendez-vous.</p></section>`,
    coach_tip: "Un rappel par SMS divise les rendez-vous manqués par 3.",
    strategic_mantra: "Laissez vos clients prendre rendez-vous quand ils en ont envie.",
    quiz_questions: [{ question: "Pourquoi la réservation en ligne ?", options: ["Pour être moderne", "Pour capter les réservations de nuit", "Pour ne plus parler"], correctAnswer: 1, explanation: "C'est un levier de croissance massif." }],
    exercises: ["Activer son lien de réservation."],
    tips: ["Affichez le lien sur Instagram."]
  },
  {
    id: "mod_parrainage",
    topic: "Vente",
    title: "Parrainage : Recruter vos clients-ambassadeurs",
    description: "Créez une machine à bouche-à-oreille automatique et rentable.",
    mini_course: "Vos meilleurs clients connaissent vos futurs meilleurs clients.",
    price: 500,
    aiCredits: 3,
    lesson_content: `<section class="lesson-card"><h2>I. L'Offre Gagnant-Gagnant</h2><p>Offrez une remise ou un soin au parrain ET au filleul.</p></section>`,
    coach_tip: "Ne donnez pas d'argent, donnez du service (soins).",
    strategic_mantra: "Le bouche-à-oreille se cultive, il ne subit pas.",
    quiz_questions: [{ question: "Qui parrainer ?", options: ["Tout le monde", "Vos meilleurs clients", "Les gens dans la rue"], correctAnswer: 1, explanation: "Ils recommandent des profils qui leur ressemblent." }],
    exercises: ["Lancer son offre de parrainage."],
    tips: ["Cartes de parrainage papier."]
  }
];

export const BADGES: Badge[] = [
  {
    id: "first_module",
    name: "Premier pas",
    icon: "🚀",
    description: "Premier module terminé.",
    condition: (u, mods) => mods.some(m => m.status === ModuleStatus.COMPLETED)
  },
  {
    id: "dedicated",
    name: "Déterminé",
    icon: "🏆",
    description: "5 modules terminés.",
    condition: (u, mods) => mods.filter(m => m.status === ModuleStatus.COMPLETED).length >= 5
  }
];

export const DIAGNOSTIC_QUESTIONS = [
  { id: 1, text: "Votre équipe est-elle formée aux techniques d'un bon accueil téléphonique ?", category: "Accueil", linkedModuleId: "mod_accueil_tel" },
  { id: 2, text: "L'équipe s'entraîne-t-elle à faire un bon diagnostic avant chaque prestation ?", category: "Technique", linkedModuleId: "mod_diagnostic" },
  { id: 3, text: "Les protocoles d'hygiène sont-ils affichés et respectés scrupuleusement par tous ?", category: "Hygiène", linkedModuleId: "mod_hygiene" },
  { id: 4, text: "Avez-vous un inventaire à jour chaque semaine pour éviter les ruptures de stock ?", category: "Gestion", linkedModuleId: "mod_stock" },
  { id: 5, text: "Publiez-vous régulièrement (au moins 3 fois par semaine) sur vos réseaux sociaux ?", category: "Digital", linkedModuleId: "mod_social_media" },
  { id: 6, text: "Utilisez-vous un fichier client pour relancer ceux qui ne sont plus venus depuis 3 mois ?", category: "Vente", linkedModuleId: "mod_fidelisation" },
  { id: 7, text: "Réalisez-vous des entretiens individuels de motivation avec vos employés chaque mois ?", category: "Management", linkedModuleId: "mod_management" },
  { id: 8, text: "Connaissez-vous précisément votre coût à la minute pour fixer vos tarifs ?", category: "Gestion", linkedModuleId: "mod_tarification" },
  { id: 9, text: "Proposez-vous systématiquement un service additionnel (soin, massage) à chaque client ?", category: "Vente", linkedModuleId: "mod_upselling" },
  { id: 10, text: "Votre taux de revente de produits représente-t-il plus de 15% de votre chiffre d'affaires ?", category: "Vente", linkedModuleId: "mod_retail" },
  { id: 11, text: "L'organisation de vos postes de travail est-elle optimisée pour éviter les pas inutiles ?", category: "Organisation", linkedModuleId: "mod_ergonomie" },
  { id: 12, text: "L'équipe porte-t-elle une tenue professionnelle harmonieuse reflétant l'image du salon ?", category: "Image", linkedModuleId: "mod_image_pro" },
  { id: 13, text: "Suivez-vous quotidiennement vos entrées/sorties d'argent sur un tableau de bord ?", category: "Gestion", linkedModuleId: "mod_tresorerie" },
  { id: 14, text: "Avez-vous une procédure écrite pour gérer calmement les réclamations clients ?", category: "Accueil", linkedModuleId: "mod_litiges" },
  { id: 15, text: "Vos clients peuvent-ils réserver leur prestation en ligne 24h/24 et 7j/7 ?", category: "Digital", linkedModuleId: "mod_booking" },
  { id: 16, text: "Avez-vous un système de parrainage actif pour attirer de nouveaux clients ?", category: "Vente", linkedModuleId: "mod_parrainage" }
];
